# Generated by Django 3.2.9 on 2021-11-04 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0001_initial'),
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colaborador',
            options={'ordering': ['-first_name', 'last_name'], 'verbose_name': 'Colaborador', 'verbose_name_plural': 'Colaboradores'},
        ),
        migrations.AddField(
            model_name='colaborador',
            name='foto',
            field=models.ImageField(blank=True, height_field=200, null=True, upload_to='colaborador', verbose_name='Imagen de Perfil'),
        ),
        migrations.AlterUniqueTogether(
            name='colaborador',
            unique_together={('first_name', 'departamento')},
        ),
    ]
