# Generated by Django 3.2.9 on 2021-11-04 14:12

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0004_colaborador_habilidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='bio',
            field=ckeditor.fields.RichTextField(default='Añadir biografia'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='last_name',
            field=models.CharField(max_length=15, verbose_name='Apellido'),
        ),
    ]
