# Generated by Django 3.2.9 on 2021-11-08 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0006_colaborador_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='full_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='Nombre Completo'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='job',
            field=models.CharField(choices=[('Contador', 'Contador'), ('Administrador', 'Administrador'), ('Economista', 'Economista'), ('Otros', 'Otros')], max_length=50, verbose_name='Cargo'),
        ),
    ]
