# Generated by Django 3.2.9 on 2021-11-15 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0008_auto_20211115_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='colaborador'),
        ),
    ]
